api/urls.py
from django.urls import path
from .views import RetrieveSMS, StaffAPIView, LoginAPIView

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view()),
    path('sms/', RetrieveSMS.as_view()),
    path('staff/', StaffAPIView.as_view()),
]

bulksms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from sms.forms import CustomPasswordResetForm, CustomPasswordResetConfirmForm
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

urlpatterns = [
    path("api/v1/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('login/', RedirectView.as_view(url='/dashboard/login/')),
    path('dashboard/', include("sms.urls")),
    path('reset-password/', PasswordResetView.as_view(form_class=CustomPasswordResetForm), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(form_class=CustomPasswordResetConfirmForm), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path, include
from django.conf.urls import url

from .views import *

app_name = 'sms'

urlpatterns = [
    path('login/',SMSLogin.as_view(),name='login'),
    path('logout/',SMSLogout.as_view(),name='logout'),
    path('admin/',BaseTemplate.as_view(),name='sms_admin'),

    # Institution CRUD
    path('institution/create/', InstitutionCreate.as_view(), name='institution_create'),
    path('institutions/', InstitutionList.as_view(), name='institution_list'),
    path('institutions/<int:pk>/update/', InstitutionUpdate.as_view(), name='institution_update'),
    path('institutions/<int:pk>/delete/', InstitutionDelete.as_view(), name='institution_delete'),

    # Staff CRUD
    path('staff/create/', StaffCreate.as_view(), name='staff_create'),
    path('staffs/', StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/update/', StaffUpdate.as_view(), name='staff_update'),
    path('staff/<int:pk>/delete/', StaffDelete.as_view(), name='staff_delete'),

    #  User CRUD
    path('user/create/', UserCreate.as_view(), name='user_create'),
    path('users/', UserList.as_view(), name='user_list'),
    path('user/delete/<int:pk>', UserDelete.as_view(), name='user_delete'),
    path('password-reset-user/<int:user_id>/', UserPwdReset.as_view(), name='password_reset_user'),
    path('password/change/', ChangePassword.as_view(), name='password_change'),

    #  Receiver CRUD
    path('receiver/create/', ReceiverCreate.as_view(), name='receiver_create'),
    path('receivers/', ReceiverList.as_view(), name='receiver_list'),
    path('receiver/delete/<int:pk>/', ReceiverDelete.as_view(), name='receiver_delete'),
    path('receiver/update/<int:pk>/', ReceiverUpdate.as_view(), name='receiver_update'),

    #  Message Group CRUD
    path('messagegroup/create/', MessageGroupCreate.as_view(), name='messagegroup_create'),
    path('messagegroup/update/<int:pk>/', MessageGroupUpdate.as_view(), name='messagegroup_update'),
    path('messagegroups/', MessageGroupList.as_view(), name='messagegroup_list'),
    path('messagegroup/delete/<int:pk>/', MessageGroupDelete.as_view(), name='messagegroup_delete'),

    # AuditTrails
    path('logs/', AuditTrailList.as_view(), name='logs'),
    path('audit/detail/<int:pk>/', AuditTrailDetail.as_view(), name='audit_detail'),

    #Message
    path('sms/create',MessageCreate.as_view(),name='message_create'),
    path('sms/list/',MessageList.as_view(),name='message_list'),
    path('words-count/',wordscount,name='words_count'),

]

sms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from shortuuid.django_fields import ShortUUIDField


AUDIT_TYPE_CHOICES = (
    (1, 'LOGIN'),
    (2, 'LOGOUT'),
    (3, 'CREATE'),
    (4, 'UPDATE'),
    (5, 'DELETE'),
    (6, 'RESET_PASSWORD'),
    (7, 'CHANGE GROUP'),
)


MESSAGE_TYPE = (
    (1, 'Recipient'),
    (2, 'Group'),
    (3, 'Bulk'),
)


USER_TYPE = (
    (1, 'Superuser'),
    (2, 'Admin'),
    (3, 'Staff'),
)


class User(AbstractUser):
    idx = ShortUUIDField(length=16, max_length=40, unique=True, editable=False)
    user_type = models.IntegerField(choices=USER_TYPE, default=1, null=True, blank=True)
    created_by = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    def is_superadmin(self):
        return True if self.user_type == 1 else False 

    def is_administration(self):
        return True if self.user_type == 2 else False 

    def is_staffuser(self):
        return True if self.user_type == 3 else False 


class DateTimeModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True, auto_now=False, null=True, blank=True)
    updated_at = models.DateTimeField(
        auto_now_add=False, auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True


class Institution(DateTimeModel):
    institution_name = models.CharField(max_length=50)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.institution_name


class Staff(User, DateTimeModel):
    institution = models.ForeignKey(Institution, null=True, blank=True, on_delete=models.CASCADE, related_name='staff_institution')
    # is_admin = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Staff"
        verbose_name_plural = "Staffs"
        ordering = ('created_at',)

    def __str__(self):
        return self.username


class Receiver(DateTimeModel):
    full_name = models.CharField(max_length=255, null=True)
    contact_number = models.BigIntegerField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="receiver_creator",)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.full_name + '/' + str(self.contact_number)


class MessageGroup(DateTimeModel):
    group_name = models.CharField(max_length=255)
    receiver = models.ManyToManyField(Receiver, blank=True)
    contacts_upload = models.FileField(null=True, blank=True, upload_to='files')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="messagegroup_creator",)


    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.group_name


class Message(DateTimeModel):
    message_type = models.IntegerField(choices=MESSAGE_TYPE,default=1)
    message = models.TextField()
    contacts_upload = models.FileField(null=True, blank=True, upload_to='files')
    receiver = models.ManyToManyField(Receiver,blank=True)
    groups = models.ManyToManyField(MessageGroup,blank=True)
    is_sent = models.BooleanField(default=False)
    recipients = models.TextField(null=True,blank=True)
    created_by = models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return str(self.id)


class AuditTrail(models.Model):
    modelType = models.CharField('Model Type', max_length=255)
    objectId = models.IntegerField('Model Id')
    action = models.IntegerField(
        choices=AUDIT_TYPE_CHOICES, default=1, null=False)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='SMS_user')
    ip = models.GenericIPAddressField(null=True)
    fromObj = models.JSONField(null=True)
    toObj = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "AuditTrail"
        verbose_name_plural = "AuditTrails"
        ordering = ('-created_at',)

    def what_is(self):
        return AUDIT_TYPE_CHOICES[self.action - 1][1]

    def __str__(self):
        return self.modelType + '(' + AUDIT_TYPE_CHOICES[self.action - 1][1] + ')'

templates/sms-2/base.html
<!--
=========================================================
* Soft UI Dashboard - v1.0.3
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'administration/img/logo.png' %}">
  <title>
    {% block title %} {% endblock title %}
  </title>

  {% block custom_css %} {% endblock custom_css %}
  {% block head_scripts %} {% endblock head_scripts %}
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Nucleo Icons -->
  <link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'assets/css/soft-ui-dashboard.css' %}" rel="stylesheet" />

  <!-- Custom CSS -->
  <link id="pagestyle" href="{% static '/assets/css/custom.css' %}" rel="stylesheet" />

  
</head>

<body class="g-sidenav-show  bg-gray-100">

  {% block main_body %}

    <!-- Sidebar -->
    {% include 'sms-2/sidebar.html' %}
    <!-- Sidebar Ends -->

    <!-- Navbar -->
    {% include 'sms-2/header.html' %}
    <!-- End Navbar -->


  {% endblock main_body %}

  <div class="fixed-plugin">
    <!-- <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
      <i class="fa fa-cog py-2"> </i>
    </a> -->
    <div class="card shadow-lg ">
      <div class="card-header pb-0 pt-3 ">
        <div class="float-start">
          {% if request.user.user_type == 1 %}
          <h5 class="mt-3 mb-0">{{ request.user.username }}</h5>
          {% else %}
          <h5 class="mt-3 mb-0">{{ request.user.first_name }} {{ request.user.last_name }}</h5>
          {% endif %}
          <p>{{ request.user.email }}</p>
        </div>
        <div class="float-end mt-4">
          <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
            <i class="fa fa-close"></i>
          </button>
        </div>
        <!-- End Toggle Button -->
      </div>
      <hr class="horizontal dark my-1">
      <div class="card-body pt-sm-3 pt-0">
        <div>
          <div class="row">
            <a href="{% url 'sms:sms_admin' %}">
              <div style="float: left;">
                <i class="fas fa-user"></i>
              </div>
              <div>
                <h6 class="mb-3" style="margin-left: 25px;">Profile</h6>
              </div>
            </a>
          </div>
        </div>
        <div>
          <div class="row">
            <a href="{% url 'sms:password_change' %}">
              <div style="float: left;">
                <i class="fas fa-key"></i>
              </div>
              <div >
                <h6 class="mb-3" style="margin-left: 25px;">Change Password</h6>
              </div>
            </a>
          </div>
        </div>
        <div>
          <div class="row">
            <form action="/dashboard/logout/" method="post">
              {% csrf_token %}
                <div style="float: left;">
                  <i class="fas fa-sign-out-alt"></i>
                </div>
                <div>
                  <button type="submit" class="nav-link font-weight-bold px-0 hide-button-style">
                    <h6 class="mb-3 text-dark" style="margin-left: 10px;">Logout</h6>
                  </button>
                </div>
            </form>
          </div>
          <!-- <h6 class="mb-3">Logout</h6> -->
        </div>
        <!-- Sidebar Backgrounds -->
        <!-- <div>
          <h6 class="mb-0">Sidebar Colors</h6>
        </div>
        <a href="javascript:void(0)" class="switch-trigger background-color">
          <div class="badge-colors my-2 text-start">
            <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
          </div>
        </a> -->
        <!-- Sidenav Type -->
        <!-- <div class="mt-3">
          <h6 class="mb-0">Sidenav Type</h6>
          <p class="text-sm">Choose between 2 different sidenav types.</p>
        </div>
        <div class="d-flex">
          <button class="btn bg-gradient-primary w-100 px-3 mb-2 active" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
          <button class="btn bg-gradient-primary w-100 px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
        </div>
        <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p> -->
        <!-- Navbar Fixed -->
        <!-- <div class="mt-3">
          <h6 class="mb-0">Navbar Fixed</h6>
        </div>
        <div class="form-check form-switch ps-0">
          <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
        </div> -->
        <hr class="horizontal dark my-sm-4">
        <!-- <a class="btn bg-gradient-dark w-100" href="https://www.creative-tim.com/product/soft-ui-dashboard-pro">Free Download</a>
        <a class="btn btn-outline-dark w-100" href="https://www.creative-tim.com/learning-lab/bootstrap/license/soft-ui-dashboard">View documentation</a>
        <div class="w-100 text-center">
          <a class="github-button" href="https://github.com/creativetimofficial/soft-ui-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/soft-ui-dashboard on GitHub">Star</a>
          <h6 class="mt-3">Thank you for sharing!</h6>
          <a href="https://twitter.com/intent/tweet?text=Check%20Soft%20UI%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fsoft-ui-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
          </a>
          <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.creative-tim.com/product/soft-ui-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
          </a>
        </div> -->
      </div>
    </div>
  </div>

  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/chartjs.min.js' %}"></script>

  {% block scripts %} {% endblock %}

  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/soft-ui-dashboard.min.js' %}"></script>

  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>

</body>

</html>

templates/sms-2/logout.html
<div id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true" class="modal fade text-left">
    <div role="document" class="modal-dialog">
        <div class="modal-content">
  
            <div class="modal-header">
                <h4 id="logoutModalLabel" class="modal-title">Logout</h4>
                <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
            </div>
  
            <form class="form" action="{% url 'sms:logout' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    Are you sure you want to Logout?
                </div>
                <div class="modal-footer">
                    <input type="submit" id="submit" class="btn btn-danger" value="Logout">
                    <button type="button" data-dismiss="modal" class="btn btn-secondary">Close</button>
                </div>
            </form>
  
        </div>
    </div>
</div>

templates/sms-2/logs.html
<!--
=========================================================
* Soft UI Dashboard - v1.0.3
=========================================================

* Product Page: https://www.creative-tim.com/product/soft-ui-dashboard
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% extends 'sms-2/base.html' %}

{% load static %}

{% block title %} Logs {% endblock title %}

  {% block main_body %}

  <!-- Sidebar -->
  {% include 'sms-2/sidebar.html' %}
  <!-- Sidebar Ends -->

  <main class="main-content position-relative max-height-vh-100 h-100 mt-1 border-radius-lg ">
  <!-- Navbar -->
  {% include 'sms-2/header.html' %}
  <!-- End Navbar -->

    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              <div class="row">
                <div class="col-lg-6 float-left">
                <h6>Logs</h6>
                </div>
                <!-- <div class="col-lg-6 float-right text-right">
                  <a class="btn btn-primary" style="position: relative; left: 89%;" href="{% url 'sms:staff_create' %}" data-toggle="tooltip" data-placement="top" title="Create">
                    <i class="fa fa-plus" style="border-radius:50%"></i>
                  </a>
                </div> -->
              </div>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">#</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Action</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Model Type</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Handled By</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Created At</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">IP Address</th>
                      <th class="text-secondary opacity-7"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for log in logs %}
                    <tr>
                      <td class="align-middle text-center">
                        <span class="text-secondary text-xs font-weight-bold">{{ forloop.counter }}</span>
                      </td>
                      <td>
                        <div class="d-flex px-2 py-1">
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{ log.get_action_display }}</h6>
                            </div>
                        </div>
                      </td>
                      <td>
                        <div class="d-flex px-2 py-1">
                            
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{ log.modelType }}</h6>
                            </div>
                        </div>
                      </td>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div>
                            <img src="{% static 'assets/img/team-2.jpg' %}" class="avatar avatar-sm me-3" alt="user1">
                          </div>
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{ log.user.username }}</h6>
                            <p class="text-xs text-secondary mb-0">{{ log.user.first_name }} {{ log.user.last_name }}</p>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle text-center font-weight-bold text-sm">
                        <span class="text-xs text-secondary mb-0">{{ log.created_at }}</span>
                      </td>
                      <td class="align-middle text-center">
                        <span class="text-secondary text-xs font-weight-bold">{{ log.ip }}</span>
                      </td>
                      <td>
                          <a href="{% url 'sms:audit_detail' log.id %}">
                            <p class="text-xs text-secondary mb-0">View Details</p>
                          </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- <footer class="footer pt-3  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>,
                made with <i class="fa fa-heart"></i> by
                <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
                for a better web.
              </div>
            </div>
            <div class="col-lg-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com" class="nav-link text-muted" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/presentation" class="nav-link text-muted" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                  <a href="https://creative-tim.com/blog" class="nav-link text-muted" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted" target="_blank">License</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer> -->
    </div>
  </main>
  {% block scripts %} {% endblock scripts %}

  {% endblock main_body %}