api/urls.py
from django.urls import path
from .views import RetrieveSMS, StaffAPIView, LoginAPIView

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view()),
    path('sms/', RetrieveSMS.as_view()),
    path('staff/', StaffAPIView.as_view()),
]

bulksms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from sms.forms import CustomPasswordResetForm, CustomPasswordResetConfirmForm
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

urlpatterns = [
    path("api/v1/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('login/', RedirectView.as_view(url='/dashboard/login/')),
    path('dashboard/', include("sms.urls")),
    path('reset-password/', PasswordResetView.as_view(form_class=CustomPasswordResetForm), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(form_class=CustomPasswordResetConfirmForm), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path, include
from django.conf.urls import url

from .views import *

app_name = 'sms'

urlpatterns = [
    path('login/',SMSLogin.as_view(),name='login'),
    path('logout/',SMSLogout.as_view(),name='logout'),
    path('admin/',BaseTemplate.as_view(),name='sms_admin'),

    # Institution CRUD
    path('institution/create/', InstitutionCreate.as_view(), name='institution_create'),
    path('institutions/', InstitutionList.as_view(), name='institution_list'),
    path('institutions/<int:pk>/update/', InstitutionUpdate.as_view(), name='institution_update'),
    path('institutions/<int:pk>/delete/', InstitutionDelete.as_view(), name='institution_delete'),

    # Staff CRUD
    path('staff/create/', StaffCreate.as_view(), name='staff_create'),
    path('staffs/', StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/update/', StaffUpdate.as_view(), name='staff_update'),
    path('staff/<int:pk>/delete/', StaffDelete.as_view(), name='staff_delete'),

    #  User CRUD
    path('user/create/', UserCreate.as_view(), name='user_create'),
    path('users/', UserList.as_view(), name='user_list'),
    path('user/delete/<int:pk>', UserDelete.as_view(), name='user_delete'),
    path('password-reset-user/<int:user_id>/', UserPwdReset.as_view(), name='password_reset_user'),
    path('password/change/', ChangePassword.as_view(), name='password_change'),

    #  Receiver CRUD
    path('receiver/create/', ReceiverCreate.as_view(), name='receiver_create'),
    path('receivers/', ReceiverList.as_view(), name='receiver_list'),
    path('receiver/delete/<int:pk>/', ReceiverDelete.as_view(), name='receiver_delete'),
    path('receiver/update/<int:pk>/', ReceiverUpdate.as_view(), name='receiver_update'),

    #  Message Group CRUD
    path('messagegroup/create/', MessageGroupCreate.as_view(), name='messagegroup_create'),
    path('messagegroup/update/<int:pk>/', MessageGroupUpdate.as_view(), name='messagegroup_update'),
    path('messagegroups/', MessageGroupList.as_view(), name='messagegroup_list'),
    path('messagegroup/delete/<int:pk>/', MessageGroupDelete.as_view(), name='messagegroup_delete'),

    # AuditTrails
    path('logs/', AuditTrailList.as_view(), name='logs'),
    path('audit/detail/<int:pk>/', AuditTrailDetail.as_view(), name='audit_detail'),

    #Message
    path('sms/create',MessageCreate.as_view(),name='message_create'),
    path('sms/list/',MessageList.as_view(),name='message_list'),
    path('words-count/',wordscount,name='words_count'),

]

sms/views.py
import os
import tempfile
from django.db.models.fields import CommaSeparatedIntegerField
import xlrd
import json
import requests

from django.contrib.auth import authenticate, login, logout
from django.core import serializers
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect, request
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.utils.crypto import get_random_string
from django.views.generic import CreateView, DeleteView, ListView, TemplateView, View, UpdateView, DetailView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.models import Group
from django.db.models import Q
from django.views.generic.edit import DeletionMixin

from .mixins import *
from .forms import *

AUDIT_CHOICES = {a[1]: a[0] for a in AUDIT_TYPE_CHOICES}


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def storeAuditTrail(prevObjModel, objModel, actionType, request):
    aTrail = AuditTrail()
    aTrail.modelType = objModel._meta.verbose_name.title()
    aTrail.objectId = objModel.pk
    aTrail.action = actionType
    aTrail.user = request.user
    aTrail.ip = get_client_ip(request)
    if prevObjModel:
        aTrail.fromObj = serializers.serialize("json", [prevObjModel])
    aTrail.toObj = serializers.serialize("json", [objModel])
    aTrail.save()


class AuthMixin(LoginRequiredMixin):
    login_url = reverse_lazy('sms:login')


class SMSLogin(TemplateView):
    template_name = "sms-2/login.html"

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            form = LoginForm()
            if user is not None:
                if user.is_active:
                    login(request, user)

                    storeAuditTrail(
                        None, user, AUDIT_CHOICES['LOGIN'], request)
                    return HttpResponseRedirect(reverse_lazy('sms:sms_admin'))
            else:
                return render(request, self.template_name, {
                    'form': form, 'user': username, 'error': 'Incorrect username or password'})


class SMSLogout(AuthMixin, View):
    template_name = 'sms-2/logout.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        storeAuditTrail(None, self.request.user, AUDIT_CHOICES['LOGOUT'], self.request)
        logout(self.request)
        return redirect('sms:login')


class BaseTemplate(AuthMixin, TemplateView):
    template_name = 'sms-2/dashboard.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context =  super().get_context_data(**kwargs)

        if user.user_type == 1:
            context = {
                'logs': AuditTrail.objects.all().exclude(
                    Q(action=1) | Q(action=2)
                    ).order_by('-created_at')[:15],
                'groups': MessageGroup.objects.all().order_by('created_by'),
                'staffs': Staff.objects.all().order_by('created_by')
            }
        elif user.user_type == 2:
            logs_by_user = AuditTrail.objects.filter(user=user).values_list('id', flat=True)
            staffs = Staff.objects.filter(created_by=user).values_list('id', flat=True)
            staff_logs = AuditTrail.objects.filter(user__in=staffs).values_list('id', flat=True)
            all_logs = list(logs_by_user) + list(staff_logs)
            final_logs = AuditTrail.objects.filter(id__in=all_logs).exclude(
                    Q(action=1) | Q(action=2)
                    ).order_by('-created_at')
            
            groups_by_user = MessageGroup.objects.filter(created_by=user).values_list('id', flat=True)
            staffs = Staff.objects.filter(created_by=user).values_list('id', flat=True)
            staff_groups = MessageGroup.objects.filter(created_by__in=staffs).values_list('id', flat=True)
            all_groups = list(groups_by_user) + list(staff_groups)
            final_groups = MessageGroup.objects.filter(id__in=all_groups).order_by('created_by', 'created_at')
            
            staffs = Staff.objects.filter(
                created_by = user).order_by('created_by')

            context = {
                'logs': final_logs[:15],
                'groups': final_groups,
                'staffs': staffs
            }

        else:
            context = {
                'logs': AuditTrail.objects.filter(user=user).exclude(
                    Q(action=1) | Q(action=2)
                    ).order_by('-created_at')[:15],
                'groups': MessageGroup.objects.filter(created_by=user).order_by('created_by'),
                'staffs': Staff.objects.filter(created_by=user).order_by('created_by')
            }

        return context


class CreateMixin(AuthMixin, CreateView):
    def form_valid(self, form):
        creater = User.objects.get(username=self.request.user)
        form.instance.created_by = creater
        obj = form.save()
        storeAuditTrail(None, obj, AUDIT_CHOICES['CREATE'], self.request)
        return super(CreateMixin, self).form_valid(form)


class UpdateMixin(AuthMixin, UpdateView):
    def form_valid(self, form):
        prev_obj = self.get_object()
        obj = form.save()
        storeAuditTrail(prev_obj, obj, AUDIT_CHOICES['UPDATE'], self.request)
        return super(UpdateMixin, self).form_valid(form)


class DeleteMixin(AuthMixin, UpdateView):
    # fields = ['deleted_at']

    def form_valid(self, form):
        form.instance.deleted_at = timezone.now()
        obj = form.save()
        obj.is_active = False
        storeAuditTrail('', obj, AUDIT_CHOICES['DELETE'], self.request)
        return super(DeleteMixin, self).form_valid(form)


# Institution CRUD
class InstitutionCreate(SuperAdminRequiredMixin, CreateMixin):
    template_name = 'institution/institution_form.html'
    form_class = InstitutionForm
    success_url = reverse_lazy('sms:institution_list')


class InstitutionList(SuperAdminRequiredMixin, ListView):
    template_name = 'institution/institution_list.html'
    context_object_name = 'institutions'
    queryset = Institution.objects.all()


class InstitutionUpdate(SuperAdminRequiredMixin, UpdateMixin):
    template_name = 'institution/institution_form.html'
    form_class = InstitutionForm
    queryset = Institution.objects.all()
    success_url = reverse_lazy('sms:institution_list')


class InstitutionDelete(SuperAdminRequiredMixin, DeleteMixin, DeletionMixin):
    model = Institution
    success_url = reverse_lazy('sms:institution_list')

    def post(self, request, pk, *args, **kwargs):
        if 'confirm_delete' in self.request.POST:
            institution = Institution.objects.get(id=pk)
            institution.deleted_at = timezone.now()
            storeAuditTrail('', institution, AUDIT_CHOICES['DELETE'], self.request)
            institution.delete()
        return redirect('sms:institution_list')


#Staff CRUD

class StaffCreate(AdminRequiredMixin, CreateMixin):
    template_name = 'staff/staff_form.html'
    form_class = StaffForm

    def get(self, request, *args, **kwargs):
        user= self.request.user
        form = StaffForm()
        if not user.is_superadmin():
            form.fields['institution'].widget = forms.HiddenInput()
            form.fields['institution'].initial = user.staff.institution
            form.fields['institution'].label = ''
            form.fields['user_type'].widget = forms.HiddenInput()
            form.fields['user_type'].initial = 3
            form.fields['user_type'].label = ''
        return render(request, 'staff/staff_form.html', {'form': form})

    def form_valid(self, form):
        creater = User.objects.get(username=self.request.user)
        form.instance.created_by = creater
        form.instance.is_staff = False
        obj = form.save()
        password = get_random_string(10)
        obj.set_password(password)
        
        msg = obj.first_name + '(' + obj.username + '), ' + 'your account has been created. Please use <strong>Username: </strong>' + obj.username + '<br> <strong>Password: </strong>' + password + '<br> to login now.'

        send_mail('Account Created', '', 'no-reply@qubit.com',
                      [obj.email], fail_silently=True, html_message=msg)

        return super(StaffCreate, self).form_valid(form)


    def get_queryset(self):
        return Staff.objects.all()

    def get_success_url(self):
        return reverse_lazy('sms:staff_list')


class StaffList(AdminRequiredMixin, ListView):
    template_name = 'staff/staff_list.html'
    context_object_name = 'staffs'

    def get_queryset(self):
        user = self.request.user
        if user.user_type == 1:
            queryset = Staff.objects.all().order_by('created_by')
        elif user.user_type == 2:
            queryset = Staff.objects.filter(
                created_by = user
            )
        
        return queryset


class StaffUpdate(AdminRequiredMixin, UpdateMixin):
    template_name = 'staff/staff_form.html'
    form_class = StaffUpdateForm

    def get_queryset(self):
        return Staff.objects.all()

    def get_success_url(self):
        return reverse_lazy('sms:staff_list')


class StaffDelete(AdminRequiredMixin, DeleteMixin):
    model = Staff
    success_url = reverse_lazy('sms:staff_list')

    def post(self, request, pk, *args, **kwargs):
        if 'confirm_delete' in self.request.POST:

templates/sms/delete_modal.html
<div id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true" class="modal fade text-left">
  <div role="document" class="modal-dialog">
    <div class="modal-content">

        <div class="modal-header">
            <h4 id="deleteModalLabel" class="modal-title">Logout</h4>
                <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>

        </div>

        <form class="form" action="" method="POST">{% csrf_token %}
            <div class="modal-body">
                Are you sure you want to Delete this item?
            </div>
            <div class="modal-footer">
                <input type="submit" id="submit" class="btn btn-danger" value="Delete">
                <button type="button" data-dismiss="modal" class="btn btn-success">Close</button>
            </div>
        </form>

    </div>
  </div>
</div>

templates/sms/footer.html
<footer class="footer bg-dark shadow align-self-end py-3 px-xl-5 w-100">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 text-center text-md-left">
        <a href="#">
          <p class="mb-2 mb-md-0 text-white">Qubit SMS&copy; {% now "Y" %}</p>
        </a>
      </div>
      <div class="col-md-6 text-center text-md-right">
        <a href="#" target="_blank" class="float-right">
          Qubit Technologies Pvt Ltd
        </a>
        <p class="mb-2 mb-md-0 text-white float-right mr-2">Powered and Maintained by</p>
      </div>
    </div>
  </div>
</footer>

templates/sms/header.html
{% load static %}

<header class="header">
  <nav class="navbar navbar-expand-lg px-4 py-2 navbar-dark bg-dark"><a href="#" class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead"><i class="fa fa-align-left text-white"></i></a><a href="{% url 'sms:sms_admin' %}" class="navbar-brand font-weight-bold text-uppercase text-base">SMS Dashboard</a>
    <ul class="ml-auto d-flex align-items-center list-unstyled mb-0">
      <li class="nav-item">
        <form id="searchForm" class="ml-auto d-lg-block">
          <div class="form-group position-relative mb-0">
            <button type="submit" style="top: 4px; left: 6px; border-radius: 100%;" class="position-absolute bg-white border-0 p-0"><i class="fa fa-search text-dark text-lg" aria-hidden="true"></i></button>
            <input type="search" placeholder="Search ..." class="form-control form-control-sm border-0 no-shadow pl-6" style="padding-left: 30px;">
          </div>
        </form>
      </li>

      <li class="nav-item dropdown ml-auto"><a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{% static 'administration/img/logo.png' %}" alt="{{ request.user }}" style="max-width: 2.5rem;" class="img-fluid rounded-circle shadow"></a>
        <div aria-labelledby="userInfo" class="dropdown-menu">
            <a href="#" class="dropdown-item">
                <strong class="d-block text-uppercase headings-font-family">{{ request.user }}</strong>
                <small>Qubit SMS</small>
            </a>
          <div class="dropdown-divider"></div>
            <a href="#" data-toggle="modal" data-target="#logout-modal" class="dropdown-item">Logout</a>
            <a href="{% url 'sms:password_change' %}"  class="dropdown-item">Change Password</a>
        </div>
      </li>

    </ul>
  </nav>
</header>

 {% include 'sms/logout.html' %}

templates/sms/sidebar_menu.html
{% load static %}

<div id="sidebar" class="sidebar py-3 bg-dark">

    <ul class="sidebar-menu list-unstyled">

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'sms:sms_admin' %}"
                 class="sidebar-link text-white {% if  request.get_full_path == url_name %}active{% endif %}">
                  <i class="fa fa-home mr-3 text-white"></i>
                  <span>Home</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'sms:user_list' %}"
                 class="sidebar-link text-white {% if '/sms/users/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-user mr-3 text-white" aria-hidden="true"></i>
                  <span>Users</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="#" data-toggle="collapse" data-target="#receiver"
                 aria-expanded="{% if '/sms/receiver/' in request.get_full_path %}true{% else %}false{% endif %}"
                 aria-controls="pages"
                 class="sidebar-link text-white {% if '/sms/receiver/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-info-circle mr-3 text-white"></i>
                  <span>Receivers</span>
              </a>
            <div id="receiver"
                 class="collapse bg-dark-dark {% if '/sms/receiver/' in request.get_full_path %}show{% else %}{% endif %}">
              <ul class="sidebar-menu list-unstyled border-left border-primary border-thick">
                <li class="sidebar-list-item">
                    <a href="{% url 'sms:receiver_list' %}"
                       class="sidebar-link text-white pl-lg-5 {% if '/sms/receivers/' in request.get_full_path %} dropdown-active{% endif %}">
                        Receivers
                    </a>
                </li>
                <li class="sidebar-list-item">
                    <a href="{% url 'sms:messagegroup_list' %}"
                       class="sidebar-link text-white pl-lg-5 {% if '/sms/messagegroups/' in request.get_full_path %} dropdown-active{% endif %}">
                       Groups
                    </a>
                </li>
              </ul>
            </div>
          </li>

        <li class="sidebar-list-item top-level-item">
              <a href="#" data-toggle="collapse" data-target="#message"
                 aria-expanded="{% if url_name == 'message' %}true{% else %}false{% endif %}"
                 aria-controls="pages"
                 class="sidebar-link text-white {% if url_name == 'message' %}true{% else %}false{% endif %}">
                  <i class="fa fa-envelope-o mr-3 text-white"></i>
                  <span>Messages</span>
              </a>
            <div id="message"
                 class="collapse bg-dark-dark {% if url_name == 'message' %}show{% else %}{% endif %}">
              <ul class="sidebar-menu list-unstyled border-left border-primary border-thick">
                <li class="sidebar-list-item">
                    <a href="{% url 'sms:message_create' %}"
                       class="sidebar-link text-white pl-lg-5 {% if url_name == 'message'  %} dropdown-active{% endif %}">
                        Create Message
                    </a>
                </li>
                <li class="sidebar-list-item">
                    <a href="{% url 'sms:message_list' %}"
                       class="sidebar-link text-white pl-lg-5 {% if url_name == 'message'  %} dropdown-active{% endif %}">
                       Message List
                    </a>
                </li>
              </ul>
            </div>
          </li>


        {% comment %}
          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'resources:resources' %}"
                 class="sidebar-link text-white {% if '/moics-admin/resource' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-clipboard mr-3 text-white"></i>
                  <span>Resources</span>
              </a>
          </li>


          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:foreign-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/foreign-nomination/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-globe mr-3 text-white" aria-hidden="true"></i>
                  <span>Foreign Nomination</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'gallery:gallery' %}"
                 class="sidebar-link text-white {% if '/moics-admin/gallery/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-picture-o mr-3 text-white" aria-hidden="true"></i>
                  <span>Gallery</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:agreement-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/agreement/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-handshake-o mr-3 text-white" aria-hidden="true"></i>
                  <span>Agreements</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:e-bulletin' %}"
                 class="sidebar-link text-white {% if '/moics-admin/e-bulletin' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-file mr-3 text-white"></i>
                  <span>E-bulletins</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:executive-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/executive/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-users mr-3 text-white" ></i>
                  <span>Executives</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:spokesperson-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/spokesperson/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-users mr-3 text-white" ></i>
                  <span>SpokesPerson</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:imageslider-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/imageslider/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-picture-o mr-3 text-white"></i>
                  <span>Image Slider</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'about_ministry:branch-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/branch/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-building mr-3 text-white"></i>
                  <span>Branch/ Division</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="#" data-toggle="collapse" data-target="#other-departments"
                 aria-expanded="{% if '/moics-admin/general-director/' in request.get_full_path or '/moics-admin/other-department/' in request.get_full_path or '/moics-admin/department-office/' in request.get_full_path %}true{% else %}false{% endif %}"
                 aria-controls="other-departments"
                 class="sidebar-link text-white
                         {% if '/moics-admin/general-director/' in request.get_full_path or '/moics-admin/other-department/' in request.get_full_path or '/moics-admin/department-office/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-building mr-3 text-white" aria-hidden="true"></i>
                  <span>Other Departments</span>
              </a>
            <div id="other-departments"
                 class="collapse bg-dark-dark {% if '/moics-admin/general-director/' in request.get_full_path or '/moics-admin/other-department/' in request.get_full_path or '/moics-admin/department-office/' in request.get_full_path %}show{% else %}{% endif %}">
              <ul class="sidebar-menu list-unstyled border-left border-primary border-thick">
                <li class="sidebar-list-item">
                    <a href="{% url 'home:general-director-list' %}" class="sidebar-link text-white pl-lg-5 {% if '/moics-admin/general-director/' in request.get_full_path %}dropdown-active{% endif %}">General Director</a>
                </li>
                <li class="sidebar-list-item">
                    <a href="{% url 'home:other-department-list' %}" class="sidebar-link text-white pl-lg-5 {% if '/moics-admin/other-department/' in request.get_full_path %}dropdown-active{% endif %}">Departments</a>
                </li>
                <li class="sidebar-list-item">
                    <a href="{% url 'home:department-office-list' %}" class="sidebar-link text-white pl-lg-5 {% if '/moics-admin/department-office/' in request.get_full_path %}dropdown-active{% endif %}">Department Offices</a>
                </li>
              </ul>
            </div>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:report-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/progress-report/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-bar-chart mr-3 text-white" aria-hidden="true"></i>
                  <span>Progress Report</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:nepal-wto-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/nepal-wto/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-handshake-o mr-3 text-white" aria-hidden="true"></i>
                  <span>Nepal & WTO</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:faq-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/faq/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-question-circle-o mr-3 text-white" aria-hidden="true"></i>
                  <span>FAQ</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'home:link-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/useful-link/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-link mr-3 text-white" aria-hidden="true"></i>
                  <span>Useful Links</span>
              </a>
          </li>

          <li class="sidebar-list-item top-level-item">
              <a href="{% url 'about_ministry:budget-list' %}"
                 class="sidebar-link text-white {% if '/moics-admin/budget/' in request.get_full_path %}active{% endif %}">
                  <i class="fa fa-money mr-3 text-white" aria-hidden="true"></i>
                  <span>Budget</span>
              </a>
          </li>
        {% endcomment %}

    </ul>
</div>