api/urls.py
from django.urls import path
from .views import RetrieveSMS, StaffAPIView, LoginAPIView

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view()),
    path('sms/', RetrieveSMS.as_view()),
    path('staff/', StaffAPIView.as_view()),
]

bulksms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from sms.forms import CustomPasswordResetForm, CustomPasswordResetConfirmForm
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

urlpatterns = [
    path("api/v1/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('login/', RedirectView.as_view(url='/dashboard/login/')),
    path('dashboard/', include("sms.urls")),
    path('reset-password/', PasswordResetView.as_view(form_class=CustomPasswordResetForm), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(form_class=CustomPasswordResetConfirmForm), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path, include
from django.conf.urls import url

from .views import *

app_name = 'sms'

urlpatterns = [
    path('login/',SMSLogin.as_view(),name='login'),
    path('logout/',SMSLogout.as_view(),name='logout'),
    path('admin/',BaseTemplate.as_view(),name='sms_admin'),

    # Institution CRUD
    path('institution/create/', InstitutionCreate.as_view(), name='institution_create'),
    path('institutions/', InstitutionList.as_view(), name='institution_list'),
    path('institutions/<int:pk>/update/', InstitutionUpdate.as_view(), name='institution_update'),
    path('institutions/<int:pk>/delete/', InstitutionDelete.as_view(), name='institution_delete'),

    # Staff CRUD
    path('staff/create/', StaffCreate.as_view(), name='staff_create'),
    path('staffs/', StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/update/', StaffUpdate.as_view(), name='staff_update'),
    path('staff/<int:pk>/delete/', StaffDelete.as_view(), name='staff_delete'),

    #  User CRUD
    path('user/create/', UserCreate.as_view(), name='user_create'),
    path('users/', UserList.as_view(), name='user_list'),
    path('user/delete/<int:pk>', UserDelete.as_view(), name='user_delete'),
    path('password-reset-user/<int:user_id>/', UserPwdReset.as_view(), name='password_reset_user'),
    path('password/change/', ChangePassword.as_view(), name='password_change'),

    #  Receiver CRUD
    path('receiver/create/', ReceiverCreate.as_view(), name='receiver_create'),
    path('receivers/', ReceiverList.as_view(), name='receiver_list'),
    path('receiver/delete/<int:pk>/', ReceiverDelete.as_view(), name='receiver_delete'),
    path('receiver/update/<int:pk>/', ReceiverUpdate.as_view(), name='receiver_update'),

    #  Message Group CRUD
    path('messagegroup/create/', MessageGroupCreate.as_view(), name='messagegroup_create'),
    path('messagegroup/update/<int:pk>/', MessageGroupUpdate.as_view(), name='messagegroup_update'),
    path('messagegroups/', MessageGroupList.as_view(), name='messagegroup_list'),
    path('messagegroup/delete/<int:pk>/', MessageGroupDelete.as_view(), name='messagegroup_delete'),

    # AuditTrails
    path('logs/', AuditTrailList.as_view(), name='logs'),
    path('audit/detail/<int:pk>/', AuditTrailDetail.as_view(), name='audit_detail'),

    #Message
    path('sms/create',MessageCreate.as_view(),name='message_create'),
    path('sms/list/',MessageList.as_view(),name='message_list'),
    path('words-count/',wordscount,name='words_count'),

]

sms/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from shortuuid.django_fields import ShortUUIDField


AUDIT_TYPE_CHOICES = (
    (1, 'LOGIN'),
    (2, 'LOGOUT'),
    (3, 'CREATE'),
    (4, 'UPDATE'),
    (5, 'DELETE'),
    (6, 'RESET_PASSWORD'),
    (7, 'CHANGE GROUP'),
)


MESSAGE_TYPE = (
    (1, 'Recipient'),
    (2, 'Group'),
    (3, 'Bulk'),
)


USER_TYPE = (
    (1, 'Superuser'),
    (2, 'Admin'),
    (3, 'Staff'),
)


class User(AbstractUser):
    idx = ShortUUIDField(length=16, max_length=40, unique=True, editable=False)
    user_type = models.IntegerField(choices=USER_TYPE, default=1, null=True, blank=True)
    created_by = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    is_deleted = models.BooleanField(default=False)

    def is_superadmin(self):
        return True if self.user_type == 1 else False 

    def is_administration(self):
        return True if self.user_type == 2 else False 

    def is_staffuser(self):
        return True if self.user_type == 3 else False 


class DateTimeModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True, auto_now=False, null=True, blank=True)
    updated_at = models.DateTimeField(
        auto_now_add=False, auto_now=True, null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True


class Institution(DateTimeModel):
    institution_name = models.CharField(max_length=50)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.institution_name


class Staff(User, DateTimeModel):
    institution = models.ForeignKey(Institution, null=True, blank=True, on_delete=models.CASCADE, related_name='staff_institution')
    # is_admin = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Staff"
        verbose_name_plural = "Staffs"
        ordering = ('created_at',)

    def __str__(self):
        return self.username


class Receiver(DateTimeModel):
    full_name = models.CharField(max_length=255, null=True)
    contact_number = models.BigIntegerField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="receiver_creator",)

    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.full_name + '/' + str(self.contact_number)


class MessageGroup(DateTimeModel):
    group_name = models.CharField(max_length=255)
    receiver = models.ManyToManyField(Receiver, blank=True)
    contacts_upload = models.FileField(null=True, blank=True, upload_to='files')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="messagegroup_creator",)


    class Meta:
        ordering = ('created_at',)

    def __str__(self):
        return self.group_name


class Message(DateTimeModel):
    message_type = models.IntegerField(choices=MESSAGE_TYPE,default=1)
    message = models.TextField()
    contacts_upload = models.FileField(null=True, blank=True, upload_to='files')
    receiver = models.ManyToManyField(Receiver,blank=True)
    groups = models.ManyToManyField(MessageGroup,blank=True)
    is_sent = models.BooleanField(default=False)
    recipients = models.TextField(null=True,blank=True)
    created_by = models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return str(self.id)


class AuditTrail(models.Model):
    modelType = models.CharField('Model Type', max_length=255)
    objectId = models.IntegerField('Model Id')
    action = models.IntegerField(
        choices=AUDIT_TYPE_CHOICES, default=1, null=False)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='SMS_user')
    ip = models.GenericIPAddressField(null=True)
    fromObj = models.JSONField(null=True)
    toObj = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "AuditTrail"
        verbose_name_plural = "AuditTrails"
        ordering = ('-created_at',)

    def what_is(self):
        return AUDIT_TYPE_CHOICES[self.action - 1][1]

    def __str__(self):
        return self.modelType + '(' + AUDIT_TYPE_CHOICES[self.action - 1][1] + ')'

sms/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from .models import *

from .middleware import get_user


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}))


class UserForm(forms.ModelForm):    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'user_type']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class InstitutionForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = ['institution_name']

    def clean_institution_name(form):
        new_institution_name = form.cleaned_data['institution_name']
        q =  Institution.objects.filter(institution_name=new_institution_name)

        if q:
            raise forms.ValidationError('Institution with that name already exists.')
        else:
            return new_institution_name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = ['first_name', 'last_name', 'username', 'email', 'user_type', 'institution']
        # if not user_type == 1:
        # labels = {
        #     'institution': None,
        #     'user_type': None,
        # }

    def clean_staff_username(form):
        new_staff_name = form.cleaned_data['username']
        q =  Staff.objects.filter(username=new_staff_name)

        if q:
            raise forms.ValidationError('A staff with that username already exists.')
        else:
            return new_staff_name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['institution'].queryset = Institution.objects.all()
        # if not self.user.user_type == 1:
            # self.fields['institution'].label = ''
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class StaffUpdateForm(forms.ModelForm):
    class Meta(StaffForm.Meta):
        model = Staff
        fields = ['first_name', 'last_name', 'username', 'email', 'user_type', 'institution']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ReceiverForm(forms.ModelForm):
    class Meta:
        model = Receiver
        fields = ['full_name', 'contact_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class MessageGroupForm(forms.ModelForm):

    receiver = forms.ModelMultipleChoiceField(
        queryset=Receiver.objects.all(), required=False,
        widget=forms.SelectMultiple(
            attrs={'class': 'select2 form-control', 'multiple': 'true'}))


    class Meta:
        model = MessageGroup
        fields = ['group_name', 'receiver', 'contacts_upload']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        receivers_by_user = Receiver.objects.filter(created_by=get_user()).values_list('id', flat=True)
        staffs = Staff.objects.filter(created_by=get_user()).values_list('id', flat=True)
        receivers = Receiver.objects.filter(created_by__in=staffs).values_list('id', flat=True)
        final_receivers= list(receivers_by_user) + list(receivers)
        final_receivers = Receiver.objects.filter(id__in=final_receivers).order_by('created_by', 'created_at')
        self.fields['receiver'].queryset = final_receivers
        for field in iter(self.fields):
            self.fields['group_name'].widget.attrs.update({
                'class': 'form-control'
            })


class MessageForm(forms.ModelForm):

    receiver = forms.ModelMultipleChoiceField(
        queryset=Receiver.objects.filter(deleted_at=None), required=False,
        widget=forms.SelectMultiple(
            attrs={'class': 'select2 form-control', 'multiple': 'true'}))

    groups = forms.ModelMultipleChoiceField(
        queryset=MessageGroup.objects.filter(deleted_at=None), required=False,
        widget=forms.SelectMultiple(
            attrs={'class': 'select2 form-control', 'multiple': 'true'}))


    class Meta:
        model = Message
        fields = ['message_type', 'message', 'receiver','groups','contacts_upload']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields['message_type'].widget.attrs.update({
                'class': 'form-control'
            })
            self.fields['message'].widget.attrs.update({
                'class': 'form-control'
            })


class ChangePasswordForm(forms.Form):    
    password = forms.CharField(
        label="New Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'id': 'pass'}),
    )
    confirm_password = forms.CharField(
        label="New password confirmation",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password', 'id': 'confirmpass'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    def clean(form):
        password = form.cleaned_data.get('password')
        confirm_password = form.cleaned_data.get('confirm_password')

        if (password == confirm_password):
            try:
                password_validation.validate_password(password, confirm_password)
                return password
            except forms.ValidationError as error:
                form.add_error('password', error)
        else:
            raise forms.ValidationError('The two password fields didn’t match.')


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label=("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'email'})
    )


class CustomPasswordResetConfirmForm(SetPasswordForm):
    error_messages = {
        'password_mismatch': ('The two password fields didn’t match.'),
    }
    new_password1 = forms.CharField(
        label=("New password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        strip=False,
    )
    new_password2 = forms.CharField(
        label=("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )

templates/message/message_form.html
{% extends 'sms/index.html' %}
{% load static %}

{% block content %}


<section class="py-5">
    <div class="row">
        <!-- Basic Form-->
        <div class="col-lg-12 mb-5">
            <div class="card">
                <div class="card-header">
                    <h3 class="h6 text-uppercase mb-0">Message Form</h3>
                </div>
                <div class="card-body">
                    <p>Create Message</p>
                    <form action="{% url 'sms:message_create' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form.media}}

                        <p><span style="color:#a00">{{ form.message_type.errors }}</span>
                            <label for="{{ form.message_type.id_for_label }}">{{form.message_type.label}}</label>
                            {{ form.message_type}}</p>


                        <p><span style="color:#a00">{{ form.message.errors }}</span>
                            <label for="{{ form.message.id_for_label }}">{{form.message.label}}</label>
                            {{ form.message}}</p>

                        <div class="message-property">
                            Words Count:<span id="count"></span> Credit :<span id="credit"></span>
                        </div>

                        <p><span style="color:#a00">{{ form.receiver.errors }}</span>
                            <label for="{{ form.receiver.id_for_label }}">{{form.receiver.label}}</label>
                            {{ form.receiver}}</p>

                        <p><span style="color:#a00">{{ form.groups.errors }}</span>
                            <label for="{{ form.groups.id_for_label }}">{{form.groups.label}}</label>
                            {{ form.groups}}</p>

                        <p><span style="color:#a00">{{ form.contacts_upload.errors }}</span>
                            <label for="{{ form.contacts_upload.id_for_label }}">{{form.contacts_upload.label}}</label>
                            {{ form.contacts_upload}}
                            <br>
                            Sample : <a href="{% static '/administration/contact.xlsx' %}">Sample </a>
                        </p>

                        <div class="form-group">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}
{% block script %}

<script type="text/javascript">
$( document ).ready(function() {
    var chkVal = $('#id_message_type').find(":selected").text();
    if(chkVal == 'Recipient'){
      $('#id_groups').parent().fadeOut('fast');
      $('#id_contacts_upload').parent().fadeOut('fast');
      $('#id_receiver').parent().fadeIn('fast');
    }
  });

$('#id_message_type').change(function(e){
    var chkVal = $('#id_message_type').find(":selected").text();
     if(chkVal == 'Recipient'){
      $('#id_groups').parent().fadeOut('fast');
      $('#id_contacts_upload').parent().fadeOut('fast');
      $('#id_receiver').parent().fadeIn('fast');
    }
        else if(chkVal == 'Group')
        {
           $('#id_receiver').parent().fadeOut('fast');
      $('#id_contacts_upload').parent().fadeOut('fast');
      $('#id_groups').parent().fadeIn('fast');
        }
        else if(chkVal == 'Bulk')
        {
          $('#id_receiver').parent().fadeOut('fast');
      $('#id_groups').parent().fadeOut('fast');
      $('#id_contacts_upload').parent().fadeIn('fast');
        }
        else
        {
           $('#id_groups').parent().fadeOut('fast');
      $('#id_contacts_upload').parent().fadeOut('fast');
      $('#id_receiver').parent().fadeOut('fast');
        }
    });






</script>

<script type="text/javascript">
$(document).ready( function(){
    $('#id_message').keyup(function(){
        var query = $(this).val();ls


        $.get('/dashboard/sms/words-count/', {query: query},   function(data){
            var respdata = JSON.parse(data);
            $('#count').html(respdata['count']);
            $('#credit').html(respdata['credit']);

        });
    });
    });
</script>
{% endblock script %}

templates/message/message_list.html
{% extends "sms/index.html" %}
 {% load static tags %}

{% block content %}
    <section class="py-5">
      <div class="row">
        <div class="col-lg-12 mb-4">
          <div class="card">
            <div class="card-header">
              <div class="col-lg-6 pull-left">
                <h6 class="text-uppercase mb-0">Message List</h6>
              </div>
              <div class="col-lg-6 pull-right text-right">
                <a class="btn btn-primary" href="{% url 'sms:message_create' %}"
                   data-toggle="tooltip" data-placement="top" title="Create"
                  ><i class="fa fa-plus" style="border-radius:50%"></i
                ></a>
              </div>
            </div>
            <div class="card-body">
              <table
                class=" display table table-bordered"
                id="detTable"
                style="width: 100%;"
              >
                <thead class="thead-dark">
                  <tr>
                    <th>#</th>
                    <th>Message</th>
                    <th>Receivers</th>
                    <th>Network</th>
                    <th>Receivers Count</th>
                    <th>Sms Credit</th>
                    <th>Delivery Status</th>
                    <th>Send On</th>
                  </tr>
                </thead>
                <tbody>
                  {% for msg in object_list %}
                  <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{msg.message}}</td>
                    <td>{{msg.recipients}}</td>
                    <td>NTC</td>
                    <td>{{msg.recipients|recipients}} </td>
                    <td>{{msg.recipients|recipients}}</td>
                    <td>{% if msg.is_sent == True %} Delivered {% else %} Queued {% endif %}</td>
                    <td>{{ msg.created_at }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% include 'sms/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}