api/urls.py
from django.urls import path
from .views import RetrieveSMS, StaffAPIView, LoginAPIView

urlpatterns = [
    path('auth/login/', LoginAPIView.as_view()),
    path('sms/', RetrieveSMS.as_view()),
    path('staff/', StaffAPIView.as_view()),
]

bulksms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from sms.forms import CustomPasswordResetForm, CustomPasswordResetConfirmForm
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)

urlpatterns = [
    path("api/v1/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('login/', RedirectView.as_view(url='/dashboard/login/')),
    path('dashboard/', include("sms.urls")),
    path('reset-password/', PasswordResetView.as_view(form_class=CustomPasswordResetForm), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(form_class=CustomPasswordResetConfirmForm), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sms/urls.py
from django.urls import path, include
from django.conf.urls import url

from .views import *

app_name = 'sms'

urlpatterns = [
    path('login/',SMSLogin.as_view(),name='login'),
    path('logout/',SMSLogout.as_view(),name='logout'),
    path('admin/',BaseTemplate.as_view(),name='sms_admin'),

    # Institution CRUD
    path('institution/create/', InstitutionCreate.as_view(), name='institution_create'),
    path('institutions/', InstitutionList.as_view(), name='institution_list'),
    path('institutions/<int:pk>/update/', InstitutionUpdate.as_view(), name='institution_update'),
    path('institutions/<int:pk>/delete/', InstitutionDelete.as_view(), name='institution_delete'),

    # Staff CRUD
    path('staff/create/', StaffCreate.as_view(), name='staff_create'),
    path('staffs/', StaffList.as_view(), name='staff_list'),
    path('staff/<int:pk>/update/', StaffUpdate.as_view(), name='staff_update'),
    path('staff/<int:pk>/delete/', StaffDelete.as_view(), name='staff_delete'),

    #  User CRUD
    path('user/create/', UserCreate.as_view(), name='user_create'),
    path('users/', UserList.as_view(), name='user_list'),
    path('user/delete/<int:pk>', UserDelete.as_view(), name='user_delete'),
    path('password-reset-user/<int:user_id>/', UserPwdReset.as_view(), name='password_reset_user'),
    path('password/change/', ChangePassword.as_view(), name='password_change'),

    #  Receiver CRUD
    path('receiver/create/', ReceiverCreate.as_view(), name='receiver_create'),
    path('receivers/', ReceiverList.as_view(), name='receiver_list'),
    path('receiver/delete/<int:pk>/', ReceiverDelete.as_view(), name='receiver_delete'),
    path('receiver/update/<int:pk>/', ReceiverUpdate.as_view(), name='receiver_update'),

    #  Message Group CRUD
    path('messagegroup/create/', MessageGroupCreate.as_view(), name='messagegroup_create'),
    path('messagegroup/update/<int:pk>/', MessageGroupUpdate.as_view(), name='messagegroup_update'),
    path('messagegroups/', MessageGroupList.as_view(), name='messagegroup_list'),
    path('messagegroup/delete/<int:pk>/', MessageGroupDelete.as_view(), name='messagegroup_delete'),

    # AuditTrails
    path('logs/', AuditTrailList.as_view(), name='logs'),
    path('audit/detail/<int:pk>/', AuditTrailDetail.as_view(), name='audit_detail'),

    #Message
    path('sms/create',MessageCreate.as_view(),name='message_create'),
    path('sms/list/',MessageList.as_view(),name='message_list'),
    path('words-count/',wordscount,name='words_count'),

]

templates/receiver/messagegroup_form.html
{% extends 'sms/index.html' %}
{% load static %}

{% block content %}


    <section class="py-5">
      <div class="row">
        <!-- Basic Form-->
        <div class="col-lg-12 mb-5">
          <div class="card">
            <div class="card-header">
              <a href="{% url 'sms:messagegroup_list' %}"
                 data-toggle="tooltip" data-placement="bottom" title="Back"
                 class="pull-left">
                <i class="fa fa-chevron-circle-left mr-3" aria-hidden="true"></i>
              </a>
              <h3 class="h6 text-uppercase mb-0">MessageGroup Form</h3>
            </div>
            <div class="card-body">
              <p>Create/Update MessageGroup</p>

              {% include 'sms/form.html' %}
              Sample : <a href="{% static '/administration/contact.xlsx' %}">Sample </a>


            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}
{%block script%}
    {%endblock script%}

templates/receiver/messagegroup_list.html
{% extends "sms/index.html" %}
 {% load static %}

{% block content %}
    <section class="py-5">
      <div class="row">
        <div class="col-lg-12 mb-4">
          <div class="card">
            <div class="card-header">
              <div class="col-lg-6 pull-left">
                <h6 class="text-uppercase mb-0">SMS Message Group List</h6>
              </div>
              <div class="col-lg-6 pull-right text-right">
                <a class="btn btn-primary" href="{% url 'sms:messagegroup_create' %}"
                   data-toggle="tooltip" data-placement="top" title="Create"
                  ><i class="fa fa-plus" style="border-radius:50%"></i
                ></a>
              </div>
            </div>
            <div class="card-body">
              <table
                class=" display table table-bordered"
                id="detTable"
                style="width: 100%;"
              >
                <thead class="thead-dark">
                  <tr>
                    <th>#</th>
                    <th>Group Name</th>
                    <th>Receivers</th>
                    <th class="action_column">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for mg in object_list %}
                  <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{mg.group_name}}</td>
                    <td>{% for receiv in mg.receiver.all %}{{receiv.full_name}}/{{receiv.contact_number}} {% endfor %}</td>
                    <td style="white-space:nowrap;">
                      <form action="{% url 'sms:messagegroup_delete' mg.pk %}" method="post">
                        {% csrf_token %}
                        <a href="{% url 'sms:messagegroup_update' mg.pk %}" class="pl-1 pr-1" data-toggle="tooltip" data-placement="top" title="Update">
                          <i class="fa fa-pencil text-success"></i>
                        </a>
                        <button class="btn btn-danger btn-circle btn-sm m-1" type="submit"
                                data-toggle="tooltip" data-placement="left" title="Delete"
                                onclick="return confirm('Are you sure you want to delete this item?')">
                          <i class="fa fa-trash" aria-hidden="true"></i>
                        </button>
                      </form>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% include 'sms/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/receiver/receiver_form.html
{% extends 'sms/index.html' %}

{% load tags %}

{% block content %}

    <section class="py-5">
      <div class="row">
        <!-- Basic Form-->
        <div class="col-lg-12 mb-5">
          <div class="card">
            <div class="card-header">
              <a href="{% url 'sms:receiver_list' %}"
                 data-toggle="tooltip" data-placement="bottom" title="Back"
                 class="pull-left">
                <i class="fa fa-chevron-circle-left mr-3" aria-hidden="true"></i>
              </a>
              <h3 class="h6 text-uppercase mb-0">Receiver Form</h3>
            </div>
            <div class="card-body">
              <p>Create/Update Receivers</p>
              <div class="line"></div>

                {% include 'sms/form.html' %}

            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/receiver/receiver_list.html
{% extends "sms/index.html" %}
 {% load static %}

{% block content %}
    <section class="py-5">
      <div class="row">
        <div class="col-lg-12 mb-4">
          <div class="card">
            <div class="card-header">
              <div class="col-lg-6 pull-left">
                <h6 class="text-uppercase mb-0">SMS Receiver List</h6>
              </div>
              <div class="col-lg-6 pull-right text-right">
                <a class="btn btn-primary" href="{% url 'sms:receiver_create' %}"
                   data-toggle="tooltip" data-placement="top" title="Create"
                  ><i class="fa fa-plus" style="border-radius:50%"></i
                ></a>
              </div>
            </div>
            <div class="card-body">
              <table
                class=" display table table-bordered"
                id="detTable"
                style="width: 100%;"
              >
                <thead class="thead-dark">
                  <tr>
                    <th>#</th>
                    <th>Full Name</th>
                    <th>Contact Number</th>
                    <th class="action_column">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for receiver in object_list %}
                  <tr>
                    <td scope="row">{{ forloop.counter }}</td>
                    <td>{{receiver.full_name}}</td>
                    <td>{{receiver.contact_number}}</td>
                    <td style="white-space:nowrap;">
                      <form action="{% url 'sms:receiver_delete' receiver.pk %}" method="post">
                        {% csrf_token %}
                        <a href="{% url 'sms:receiver_update' receiver.pk %}" class="pl-1 pr-1" data-toggle="tooltip" data-placement="top" title="Update">
                          <i class="fa fa-pencil text-success"></i>
                        </a>
                        <button class="btn btn-danger btn-circle btn-sm m-1" type="submit"
                                data-toggle="tooltip" data-placement="left" title="Delete"
                                onclick="return confirm('Are you sure you want to delete this item?')">
                          <i class="fa fa-trash" aria-hidden="true"></i>
                        </button>
                      </form>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% include 'sms/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}